name: test-airflow

services:
  scheduler:
    build:
      context: airflow
      dockerfile: Dockerfile.scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      # Update this connection string to point to your remote PostgreSQL
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/postgres?options=-csearch_path%3Dairflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_SCHEMA: airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "test"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW_CONN_POSTGRES_DB_CONN: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/postgres
      AIRFLOW_CONN_MINIO_CONN: aws://minioadmin:minioadmin@/?endpoint_url=http://minio:9000
      AIRFLOW_CONN_WASB__CONN: wasb://DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      # TODO: enable CORS on production
    command: airflow scheduler
