name: Publish release images to Github Registry

on:
  push:
    branches:
      - "main"

env:
  app-name: test-airflow
  repo-owner: ${{ github.repository_owner }}
  registry: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timestamp env var
        run: echo "RUN_TIMESTAMP=$(TZ="Etc/UTC" date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Tag and for backend
      - name: Extract backend Docker metadata
        id: backend_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.app-name }}/airflow
          tags: |
            ${{ github.event.release.tag_name }}
            ${{ github.sha }}
            ${{ env.RUN_TIMESTAMP }}
            "latest"

      - name: Build and push backend image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./airflow
          file: ./airflow/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.backend_meta.outputs.tags }}
